# Generated by Django 4.2 on 2023-05-04 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='task',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.task', verbose_name='Tarea'),
        ),
    ]
