# Generated by Django 4.2 on 2023-05-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_messages_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='checkout',
            field=models.BooleanField(default=False, verbose_name='Hecho'),
        ),
    ]
